name = "todo-list"
main = "src/worker.ts"
compatibility_date = "2023-07-10"

kv_namespaces =[
  { binding = "TODOS", id="283ac82ce60b40fa8cc017d6173d69dc", preview_id = "fcbd676f82a4448ba4231e0bfb201bb6"}
]